# Generated by Django 3.1.5 on 2022-11-20 23:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0003_auto_20160729_2008"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="site",
            options={
                "ordering": ["domain"],
                "verbose_name": "site",
                "verbose_name_plural": "sites",
            },
        ),
    ]
