# Generated by Django 3.2.20 on 2023-10-25 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0018_institution_archival'),
        ('parcels', '0002_auto_20181021_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingparcelpost',
            name='created_by',
            field=models.ForeignKey(help_text='Created by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incomingparcelpost',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institution', verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='outgoingparcelpost',
            name='created_by',
            field=models.ForeignKey(help_text='Created by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outgoingparcelpost',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institution', verbose_name='Recipient'),
        ),
    ]
