# Generated by Django 2.2.24 on 2021-10-04 02:20

from django.db import migrations, models
import feder.parcels.models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_auto_20181021_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingparcelpost',
            name='content',
            field=models.FileField(upload_to=feder.parcels.models.parcel_upload_to, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='outgoingparcelpost',
            name='content',
            field=models.FileField(upload_to=feder.parcels.models.parcel_upload_to, verbose_name='Content'),
        ),
    ]
