# Generated by Django 4.2.11 on 2024-03-21 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20211021_0249'),
        ('parcels', '0003_auto_20231025_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingparcelpost',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='records.record'),
        ),
        migrations.AlterField(
            model_name='outgoingparcelpost',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='records.record'),
        ),
    ]
