# This is Dockerfile for development purposes only.
ARG PYTHON_VERSION='3.10.12'
FROM python:${PYTHON_VERSION}-slim
RUN python --version
RUN mkdir /code /code/production
WORKDIR /code

# Install python dependencies
ENV PYTHONUNBUFFERED 1
RUN apt-get update \
&& apt-get install -y --no-install-recommends \
   python3-dev default-libmysqlclient-dev build-essential \
   default-mysql-client libssl-dev pkg-config \
   gcc \
   build-essential \
   git \
   curl \
   nano \
   htop \
   gettext libgettextpo-dev wait-for-it
RUN pip install --upgrade pip
RUN pip --version
COPY requirements/*.txt ./requirements/
RUN touch -a secrets_Azure_OpenAI.env
RUN touch -a secrets_imap-to-webhook-url.env
ARG DJANGO_VERSION='==3.2.20'
RUN bash -c "if [[ "${DJANGO_VERSION}" == 'master' ]]; then \
pip install --no-cache-dir -r requirements/dev.txt https://github.com/django/django/archive/master.tar.gz; else \
pip install --no-cache-dir -r requirements/dev.txt \"django${DJANGO_VERSION}\"; fi"
# CMD ["bash", "-c", "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
# to allow VScode run and debug django app:
CMD ["bash", "-c", "python manage.py collectstatic --no-input && python manage.py migrate && sleep infinity"]
# to debug container starting errors:
# CMD ["bash", "-c", "python manage.py collectstatic --no-input ; python manage.py migrate ; sleep infinity"]
