FROM node:22
WORKDIR /app
VOLUME /app
CMD ["bash","-c", "npm install && npx update-browserslist-db@latest && npm rebuild node-sass && npx gulp build"]
#CMD ["bash","-c", " npm install ; npm rebuild node-sass ; npx gulp build ; sleep infinity "]
