# Generated by Django 4.2.19 on 2025-04-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus_scan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='engine_report',
            field=models.JSONField(blank=True, verbose_name='Engine result'),
        ),
    ]
