# Generated by Django 4.2.19 on 2025-04-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus_scan', '0002_alter_request_engine_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='engine_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='request',
            name='engine_link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Engine result URL'),
        ),
        migrations.AlterField(
            model_name='request',
            name='engine_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Engine name'),
        ),
        migrations.AlterField(
            model_name='request',
            name='engine_report',
            field=models.JSONField(blank=True, null=True, verbose_name='Engine result'),
        ),
    ]
