# Generated by Django 4.2.20 on 2025-04-26 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('virus_scan', '0004_alter_request_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Scan of'),
        ),
    ]
