# Generated by Django 4.2.20 on 2025-04-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus_scan', '0005_alter_request_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Scan object ID'),
        ),
    ]
