# Generated by Django 4.2.21 on 2025-05-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus_scan', '0007_engineapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineapikey',
            name='url',
            field=models.CharField(default='https://api.metadefender.com', max_length=200),
        ),
    ]
