# Generated by Django 5.2.13 on 2026-04-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('virus_scan', '0008_alter_engineapikey_url'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='request',
            new_name='scanreq_ct_obj_idx',
            old_name='virus_scan__content_e045f6_idx',
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status', 'engine_name', 'created'], name='scanreq_stat_eng_created_idx'),
        ),
    ]
