# Generated by Django 2.2.17 on 2021-01-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0019_auto_20210128_2204"),
        ("cases_tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(db_index=True, max_length=250, verbose_name="Name"),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("monitoring", "name")},
        ),
    ]
