# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 02:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0002_auto_20151025_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='solver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_solver', to=settings.AUTH_USER_MODEL, verbose_name='Solver'),
        ),
    ]
