# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_solver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['created'], 'verbose_name': 'Alert', 'verbose_name_plural': 'Alerts'},
        ),
    ]
