# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_auto_20151025_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='record',
            new_name='letter',
        ),
    ]
