# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("letters", "0003_auto_20160729_2008")]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="email",
            field=models.EmailField(blank=True, max_length=100, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="letter",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
    ]
