# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0005_letter_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='eml',
            field=models.FileField(blank=True, null=True, upload_to=b'messages/%Y/%m/%d', verbose_name='File'),
        ),
    ]
