# Generated by Django 1.11.10 on 2018-02-19 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("letters", "0011_letter_is_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="mark_spam_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The person who marked it as spam",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="letter_mark_spam_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name=b"Spam marker",
            ),
        )
    ]
