# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 18:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letters', '0013_letter_mark_spam_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='mark_hidden_by',
            field=models.ForeignKey(blank=True, help_text='The person who hid the letter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_mark_hidden_by', to=settings.AUTH_USER_MODEL, verbose_name='Hiding person'),
        ),
    ]
