# Generated by Django 1.11.10 on 2018-02-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("letters", "0015_letter_way")]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="way",
            field=models.IntegerField(
                choices=[(0, "Traditional"), (1, "E-mail"), (2, "Other")], default=1
            ),
        )
    ]
