# Generated by Django 1.11.10 on 2018-02-27 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("letters", "0017_auto_20180227_1908")]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="record",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="letters_letter_related",
                related_query_name="letters_letters",
                to="records.Record",
            ),
        )
    ]
