# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0018_auto_20180227_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='case',
        ),
    ]
