# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0019_remove_letter_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='way',
        ),
    ]
