# Generated by Django 2.2.16 on 2020-11-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0022_remove_letter_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="html_body",
            field=models.TextField(blank=True, verbose_name="Text in HTML"),
        ),
        migrations.AddField(
            model_name="letter",
            name="html_quote",
            field=models.TextField(blank=True, verbose_name="Quote in HTML"),
        ),
    ]
