# Generated by Django 2.2.17 on 2021-01-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0023_auto_20201118_1754"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="message_type",
            field=models.IntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "Regular"),
                    (2, "Disposition notification"),
                    (3, "Vacation reply"),
                ],
                default=0,
                verbose_name="Message type",
            ),
        ),
    ]
