# Generated by Django 2.2.19 on 2021-04-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases_tags", "0003_casetag"),
        ("letters", "0024_letter_message_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="recipients_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Used in mass message draft to determine recipients by case tags.",
                to="cases_tags.Tag",
                verbose_name="Recipient tags",
            ),
        ),
        migrations.AlterField(
            model_name="letter",
            name="message_type",
            field=models.IntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "Regular"),
                    (2, "Disposition notification"),
                    (3, "Vacation reply"),
                    (4, "Mass message draft"),
                ],
                default=0,
                verbose_name="Message type",
            ),
        ),
    ]
