# Generated by Django 2.2.19 on 2021-04-21 13:12

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cases_tags", "0003_casetag"),
        ("monitorings", "0021_auto_20210203_1950"),
        ("letters", "0024_letter_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="message_type",
            field=models.IntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "Regular"),
                    (2, "Disposition notification"),
                    (3, "Vacation reply"),
                    (4, "Mass message draft"),
                ],
                default=0,
                verbose_name="Message type",
            ),
        ),
        migrations.CreateModel(
            name="MassMessageDraft",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "letter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="letters.Letter",
                        verbose_name="Letter",
                    ),
                ),
                (
                    "monitoring",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitorings.Monitoring",
                        verbose_name="Monitoring",
                    ),
                ),
                (
                    "recipients_tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Used to determine recipients by case tags.",
                        to="cases_tags.Tag",
                        verbose_name="Recipient tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mass message draft",
                "verbose_name_plural": "Mass message drafts",
            },
        ),
    ]
