# Generated by Django 2.2.19 on 2021-05-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0025_auto_20210421_1312"),
    ]

    operations = [
        migrations.AlterField(
            model_name="massmessagedraft",
            name="letter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mass_draft",
                to="letters.Letter",
                verbose_name="Letter",
            ),
        ),
    ]
