# Generated by Django 2.2.24 on 2021-10-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0026_auto_20210505_1327"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="letter",
            index=models.Index(
                fields=["created"], name="letters_let_created_533a4c_idx"
            ),
        ),
    ]
