# Generated by Django 3.2.16 on 2023-02-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letters", "0027_auto_20211021_0248"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="email_from",
            field=models.EmailField(
                blank=True, max_length=100, null=True, verbose_name="From email address"
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="email_to",
            field=models.EmailField(
                blank=True, max_length=100, null=True, verbose_name="To email address"
            ),
        ),
        migrations.AlterField(
            model_name="letter",
            name="is_spam",
            field=models.IntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "Non-spam"),
                    (2, "Spam"),
                    (3, "Probable spam"),
                ],
                db_index=True,
                default=0,
                verbose_name="Is SPAM?",
            ),
        ),
    ]
