# Generated by Django 3.2.19 on 2023-05-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0031_letteremaildomain_is_non_spammer_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Subject'),
        ),
    ]
