# Generated by Django 3.2.19 on 2023-06-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0032_alter_letter_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letteremaildomain',
            options={'verbose_name': 'Letter Email domain', 'verbose_name_plural': 'Letter Email domains'},
        ),
    ]
