# Generated by Django 3.2.19 on 2023-06-22 12:25

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0033_alter_letteremaildomain_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReputableLetterEmailTLD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Email address repurable TLD')),
            ],
            options={
                'verbose_name': 'Reputable Letter Email TLD',
                'verbose_name_plural': 'Reputable Letter Email TLDs',
            },
        ),
    ]
