# Generated by Django 3.2.19 on 2023-06-22 14:55

from django.db import migrations, models
import feder.letters.models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0034_reputableletteremailtld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reputableletteremailtld',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[feder.letters.models.validate_tld_name], verbose_name='Email address repurable TLD'),
        ),
    ]
