# Generated by Django 3.2.20 on 2023-08-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0035_alter_reputableletteremailtld_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='text_content',
            field=models.TextField(blank=True, null=True, verbose_name='Text content'),
        ),
    ]
