# Generated by Django 3.2.20 on 2023-10-25 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitorings', '0029_auto_20231025_1511'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0018_institution_archival'),
        ('letters', '0038_letter_ai_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='author_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.institution', verbose_name='Author (if institution)'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Author (if user)'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='mark_spam_by',
            field=models.ForeignKey(blank=True, help_text='The person who marked it as spam', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='letter_mark_spam_by', to=settings.AUTH_USER_MODEL, verbose_name='Spam marker'),
        ),
        migrations.AlterField(
            model_name='massmessagedraft',
            name='letter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mass_draft', to='letters.letter', verbose_name='Letter'),
        ),
        migrations.AlterField(
            model_name='massmessagedraft',
            name='monitoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitorings.monitoring', verbose_name='Monitoring'),
        ),
    ]
