# Generated by Django 3.2.20 on 2023-10-27 14:56

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0039_auto_20231025_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='normalized_response',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Normalized monitoring response'),
        ),
    ]
