# Generated by Django 3.2.20 on 2023-11-20 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0040_letter_normalized_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massmessagedraft',
            name='letter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mass_draft', to='letters.letter', verbose_name='Letter'),
        ),
    ]
