# Generated by Django 4.2.13 on 2024-05-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0042_alter_letter_record'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='letter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('author_institution__isnull', True), ('author_user__isnull', False)), models.Q(('author_institution__isnull', False), ('author_user__isnull', True)), models.Q(('author_institution__isnull', True), ('author_user__isnull', True)), _connector='OR'), name='only_one_or_none_author'),
        ),
    ]
