# Generated by Django 4.2.21 on 2025-05-16 13:18

from django.db import migrations
from django.utils import timezone
import django_extensions.db.fields


def copy_letter_dates(apps, schema_editor):
    Attachment = apps.get_model("letters", "Attachment")
    for attachment in Attachment.objects.all():
        if attachment.letter_id:
            letter = attachment.letter
            attachment.created = getattr(letter, "created", timezone.now())
            attachment.modified = getattr(letter, "modified", timezone.now())
            attachment.save(update_fields=["created", "modified"])


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0043_letter_only_one_or_none_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={"get_latest_by": "modified"},
        ),
        migrations.AddField(
            model_name="attachment",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                null=True,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True,
                null=True,
                verbose_name="modified",
            ),
        ),
        migrations.RunPython(copy_letter_dates, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="attachment",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                verbose_name="created",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True,
                verbose_name="modified",
            ),
        ),
    ]
