# Generated by Django 5.2.10 on 2026-01-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0044_alter_attachment_options_attachment_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(max_length=500, upload_to='letters/%Y/%m/%d', verbose_name='File'),
        ),
    ]
