# Generated by Django 5.2.10 on 2026-01-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0045_alter_attachment_options_alter_attachment_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Subject'),
        ),
    ]
