# Generated by Django 5.2.13 on 2026-04-14 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0020_alter_institution_parents'),
        ('letters', '0046_alter_letter_title'),
        ('records', '0003_auto_20211021_0249'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='letter',
            index=models.Index(fields=['created'], name='letter_created_idx'),
        ),
        migrations.AddIndex(
            model_name='letter',
            index=models.Index(fields=['is_spam', 'created'], name='letter_spam_created_idx'),
        ),
        migrations.AddIndex(
            model_name='letter',
            index=models.Index(fields=['record', 'created'], name='letter_record_created_idx'),
        ),
        migrations.AddIndex(
            model_name='letter',
            index=models.Index(fields=['email_from', 'email_to', 'title'], name='letter_from_to_title_idx'),
        ),
    ]
