# Generated by Django 1.11.11 on 2018-08-27 21:51

from django.db import migrations


def update_domain_forward(apps, schema_editor):
    """Set site domain and name."""
    Domain = apps.get_model("domains", "Domain")
    Domain.objects.update_or_create(pk=1, name="fedrowanie.siecobywatelska.pl")


class Migration(migrations.Migration):

    dependencies = [("domains", "0001_initial")]

    operations = [migrations.RunPython(update_domain_forward)]
