# Generated by Django 3.2.20 on 2023-10-25 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('domains', '0003_domain_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organisations.organisation', verbose_name='Organisation'),
        ),
    ]
