# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorings', '0002_auto_20151025_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='template',
            field=models.TextField(default='', verbose_name='Template'),
            preserve_default=False,
        ),
    ]
