# Generated by Django 1.11.9 on 2018-01-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("monitorings", "0008_monitoring_email_footer")]

    operations = [
        migrations.AddField(
            model_name="monitoring",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="Is public visible?"),
        )
    ]
