# Generated by Django 1.11.11 on 2018-08-29 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("domains", "0002_initial-domain"),
        ("monitorings", "0012_auto_20180325_2244"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoring",
            name="domain",
            field=models.ForeignKey(
                default=1,
                help_text="Domain used to sends emails",
                on_delete=django.db.models.deletion.CASCADE,
                to="domains.Domain",
            ),
            preserve_default=False,
        )
    ]
