# Generated by Django 2.2.17 on 2021-02-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0019_auto_20210128_2204"),
        ("monitorings", "0019_auto_20210128_1209"),
    ]

    operations = []
