# Generated by Django 2.2.24 on 2021-09-20 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monitorings", "0021_auto_20210203_1950"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monitoring",
            options={
                "ordering": ["created"],
                "permissions": (
                    ("add_case", "Can add case"),
                    ("change_case", "Can change case"),
                    ("delete_case", "Can delete case"),
                    ("view_quarantined_case", "Can view quarantine cases"),
                    ("add_letter", "Can add letter"),
                    ("reply", "Can reply"),
                    ("add_draft", "Add reply draft"),
                    ("change_letter", "Can change letter"),
                    ("delete_letter", "Can delete letter"),
                    ("view_alert", "Can view alert"),
                    ("change_alert", "Can change alert"),
                    ("delete_alert", "Can delete alert"),
                    ("manage_perm", "Can manage perms"),
                    ("view_log", "Can view logs"),
                    ("spam_mark", "Can mark spam"),
                    ("add_parcelpost", "Can add parcel post"),
                    ("change_parcelpost", "Can change parcel post"),
                    ("delete_parcelpost", "Can delete parcel post"),
                    ("view_email_address", "Can view e-mail address"),
                    ("view_tag", "Can view tag"),
                    ("change_tag", "Can change tag"),
                    ("delete_tag", "Can delete tag"),
                    ("view_report", "Can view report"),
                ),
                "verbose_name": "Monitoring",
                "verbose_name_plural": "Monitoring",
            },
        ),
    ]
