# Generated by Django 2.2.27 on 2022-07-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0023_monitoring_hide_new_cases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoring",
            name="hide_new_cases",
            field=models.BooleanField(
                default=False, verbose_name="Are new cases hidden?"
            ),
        ),
    ]
