# Generated by Django 3.2.19 on 2023-06-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorings', '0023_monitoring_hide_new_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Subject'),
        ),
    ]
