# Generated by Django 2.2.27 on 2022-07-30 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0024_auto_20220730_1850"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitoring",
            name="hide_new_cases",
        ),
    ]
