# Generated by Django 2.2.27 on 2022-07-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0025_remove_monitoring_hide_new_cases"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoring",
            name="hide_new_cases",
            field=models.BooleanField(
                default=False, verbose_name="Should new cases be hidden?"
            ),
        ),
    ]
