# Generated by Django 2.2.27 on 2022-08-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0026_monitoring_hide_new_cases"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitoring",
            name="hide_new_cases",
        ),
    ]
