# Generated by Django 3.2.20 on 2023-10-20 10:01

from django.db import migrations, models
import feder.monitorings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('monitorings', '0026_alter_monitoring_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='template',
            field=models.TextField(help_text='Use {{EMAIL}} for insert reply address', validators=[feder.monitorings.validators.validate_template_syntax, feder.monitorings.validators.validate_nested_lists], verbose_name='Template'),
        ),
    ]
