# Generated by Django 3.2.20 on 2023-10-25 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_domain_organisation'),
        ('monitorings', '0027_alter_monitoring_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='domain',
            field=models.ForeignKey(help_text='Domain used to sends emails', on_delete=django.db.models.deletion.PROTECT, to='domains.domain'),
        ),
    ]
