# Generated by Django 2.2.27 on 2022-08-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0027_remove_monitoring_hide_new_cases"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoring",
            name="hide_new_cases",
            field=models.BooleanField(
                default=False, verbose_name="Hide new cases when assigning?"
            ),
        ),
    ]
