# Generated by Django 3.2.20 on 2023-10-25 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitorings', '0028_alter_monitoring_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='monitoringgroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitorings.monitoring'),
        ),
        migrations.AlterField(
            model_name='monitoringuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitorings.monitoring'),
        ),
    ]
