# Generated by Django 3.2.20 on 2023-10-26 15:03

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('monitorings', '0029_auto_20231025_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='normalized_response_template',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Normalized response template'),
        ),
    ]
