# Generated by Django 3.2.20 on 2023-10-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorings', '0031_alter_monitoring_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='use_llm',
            field=models.BooleanField(default=False, help_text='Use LLM to evaluate responses', verbose_name='Use LLM'),
        ),
    ]
