# Generated by Django 3.2.24 on 2024-02-13 17:11

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('monitorings', '0032_monitoring_use_llm'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='responses_chat_context',
            field=jsonfield.fields.JSONField(blank=True, help_text='Monitoring responses context for AI chat', null=True, verbose_name='Responses chat context'),
        ),
    ]
