# Generated by Django 4.2.13 on 2024-05-10 12:22

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('monitorings', '0033_monitoring_responses_chat_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='normalized_response_answers_categories',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Normalized response answers categories'),
        ),
    ]
