# Generated by Django 4.2.13 on 2024-05-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorings', '0034_monitoring_normalized_response_answers_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='letter_normalization_prompt_extension',
            field=models.TextField(blank=True, null=True, verbose_name='Letter normalization prompt extension'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='letter_normalization_prompt_extension_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letter normalization prompt extension modified'),
        ),
    ]
