# Generated by Django 4.2.26 on 2025-11-14 17:11

from django.db import migrations, models
import feder.monitorings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('monitorings', '0035_monitoring_letter_normalization_prompt_extension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='template',
            field=models.TextField(help_text='Use: {{EMAIL}} to insert reply address, {{ADRESAT}} to insert addressee name', validators=[feder.monitorings.validators.validate_template_syntax, feder.monitorings.validators.validate_nested_lists], verbose_name='Template'),
        ),
    ]
