# Generated by Django 5.2.17 on 2026-09-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0036_alter_monitoring_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoring",
            name="internal_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Internal notes about this monitoring (e.g. why it was started, inspiration links, why these institutions were chosen). Never shown publicly - visible only to users who can edit this monitoring.",
                verbose_name="Internal notes",
            ),
        ),
    ]
