# Generated by Django 2.2.24 on 2021-10-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0002_auto_20180819_2314"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="record",
            index=models.Index(
                fields=["created"], name="records_rec_created_081f6d_idx"
            ),
        ),
    ]
