# Generated by Django 2.0.3 on 2018-03-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("logs", "0004_auto_20180116_2202")]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("ok", "Delivered"),
                    ("spambounce", "Spam-bounce"),
                    ("softbounce", "Soft-bounce"),
                    ("hardbounce", "Hard-bounce"),
                    ("dropped", "Dropped"),
                    ("deferred", "Deferred"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=20,
            ),
        )
    ]
