# Generated by Django 3.2.19 on 2023-06-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_auto_20180325_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['created'], 'verbose_name': 'Email log', 'verbose_name_plural': 'Email logs'},
        ),
    ]
