# Generated by Django 2.0.3 on 2018-03-25 22:44

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cases", "0006_alias")]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique=True, verbose_name="Slug"
            ),
        )
    ]
