# Generated by Django 2.2.10 on 2020-02-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0008_case_mass_assign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="email",
            field=models.CharField(db_index=True, max_length=75),
        ),
    ]
