# Generated by Django 2.2.10 on 2020-03-27 00:40

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0009_auto_20200222_1648"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="case",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                max_length=110,
                populate_from="name",
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
