# Generated by Django 2.2.17 on 2021-02-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0011_case_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="confirmation_received",
            field=models.BooleanField(
                default=False, verbose_name="Confirmation received"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="response_received",
            field=models.BooleanField(default=False, verbose_name="Response received"),
        ),
    ]
