# Generated by Django 2.2.19 on 2021-03-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_case_status"),
        ("cases_tags", "0003_casetag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="tags",
        ),
        migrations.AddField(
            model_name="case",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                through="cases_tags.CaseTag",
                to="cases_tags.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
