# Generated by Django 2.2.24 on 2021-09-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0014_auto_20210311_1445"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="is_quarantied",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Quarantied"
            ),
        ),
    ]
