# Generated by Django 3.2.19 on 2023-06-13 16:23

from django.db import migrations, models
import django.db.models.deletion


def get_first_request(apps, schema_editor):
    Letter = apps.get_model("letters", "Letter")
    Case = apps.get_model("cases", "Case")
    for case in Case.objects.all():
        first_request = Letter.objects.filter(
            record__case=case.pk, author_user_id__isnull=False
        ).order_by("created").first()
        if first_request is None:
            print(f"Case {case.pk} has no first request")
            continue
        print(f"Assigning first request {first_request.pk} to case {case.pk}")
        case.first_request = first_request
        case.save()


def get_last_request(apps, schema_editor):
    Case = apps.get_model("cases", "Case")
    Letter = apps.get_model("letters", "Letter")
    for case in Case.objects.all():
        last_request_qs = Letter.objects.filter(
            record__case=case.pk, author_user_id__isnull=False
        ).order_by("created")
        if len(last_request_qs) > 1:
            last_request = last_request_qs.last()
            print(f"Assigning last request {last_request.pk} to case {case.pk}")
            case.last_request = last_request
            case.save()
        else:
            print(f"Case {case.pk} has no last request")

class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0033_alter_letteremaildomain_options'),
        ('cases', '0016_auto_20211021_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='first_request',
            field=models.ForeignKey(
                blank=True, 
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='first_request',
                to='letters.letter',
                verbose_name='First request'
            ),
        ),
        migrations.AddField(
            model_name='case',
            name='last_request',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='last_request',
                to='letters.letter',
                verbose_name='Last request'
            ),
        ),
        migrations.RunPython(get_first_request),
        migrations.RunPython(get_last_request),
    ]
