# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('institutions', '0004_auto_20160907_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=15, unique=True, verbose_name='Name'),
        ),
    ]
