# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('institutions', '0005_auto_20160907_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['priority', 'institution'], 'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterUniqueTogether(
            name='email',
            unique_together={('institution', 'email')},
        ),
    ]
