# Generated by Django 1.9.9 on 2016-09-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("institutions", "0006_auto_20160907_2016")]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="priority",
            field=models.SmallIntegerField(
                default=0,
                help_text="Respect of confidence",
                verbose_name="Priority of usage",
            ),
        )
    ]
