# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("institutions", "0010_auto_20170808_0252")]

    operations = []
