# Generated by Django 1.11.2 on 2017-08-08 03:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("institutions", "0010_auto_20170808_0252")]

    operations = []
