# Generated by Django 1.11.2 on 2017-08-10 21:18

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [("institutions", "0012_auto_20170808_0309")]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="extra",
            field=jsonfield.fields.JSONField(
                blank=True, verbose_name=b"Unorganized additional information"
            ),
        )
    ]
