# Generated by Django 5.2.17 on 2026-09-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0020_alter_institution_parents"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="bip_url",
            field=models.URLField(blank=True, verbose_name="BIP address"),
        ),
        migrations.AddField(
            model_name="institution",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
    ]
