name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
      - uses: pre-commit/action@v2.0.0
        if: github.event_name == 'push'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: pre-commit/action@v2.0.0
        if: github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
