# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.contrib.auth.validators

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20160729_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'},
                                   help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                                   max_length=150, unique=True, verbose_name='username', 
                                   validators=[django.contrib.auth.validators.ASCIIUsernameValidator()]),
        ),
    ]
