# Generated by Django 2.2.6 on 2019-10-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0005_auto_20180326_0005")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        )
    ]
