# Generated by Django 3.2.25 on 2024-03-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20221120_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_content_editor',
            field=models.BooleanField(default=False, help_text='Whether or not to show user tinycontent editable fields', verbose_name='Content Editor'),
        ),
    ]
