# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("tasks", "0002_auto_20151025_2345")]

    operations = [
        migrations.RenameField(model_name="answer", old_name="blob", new_name="content")
    ]
